### Create an Item ###
POST http://localhost:5000/account
Content-Type: application/json

{
    "name":"test account-1",
    "industry":"test-industy-2",
    "website": "http://localhost:5000/account",
    "address": "test-address",
    "notes": "test-notes",
}

###

### Get All account ###
GET http://localhost:5000/account

###

### Update an Item ###
PUT http://localhost:5000/account/1
Content-Type: application/json

{
    "name": "Updated Item 1",
    "description": "Updated description for Item 1"
}

###

### Delete an Item ###
DELETE http://localhost:5000/account/1

###
